### ISSUE TITLE
Some problems in training for AMOS2022

### ISSUE THREAD

**Issue by SanmAIGO** [MASILab/3DUX-Net#32]
(uxnet3d) ai-team1@aiteam1:~/lxs/3DUX-Net$ python main_finetune.py --root ../datasets/AMOS2022 --output ./results/AMOS2022/ --dataset amos --network 3DUXNET --mode train --pretrain_classes 16 --batch_size 1 --crop_sample 2 --lr 0.0001 --optim AdamW --max_iter 40000 --eval_step 500 --gpu 0 --cache_rate 0.2 --num_workers 2
Used GPU: 0
Start to load data from directory: ../datasets/AMOS2022
Finished loading all training samples from dataset: amos!
Number of classes for segmentation: 16
Cropping 2 sub-volumes for training!
Performed Data Augmentations for all samples!
Start caching datasets!
Loading dataset: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 48/48 [01:13<00:00,  1.53s/it]
Chosen Network Architecture: 3DUXNET
Loss for training: DiceCELoss
Optimizer for training: AdamW, learning rate: 0.0001
Maximum Iterations for training: 40000
Training (199 / 40000 Steps) (loss=2.06485):  83%|█████████████████████████████████████████████████████████████████             | 200/240 [05:40<01:08,  1.70s/it]
Traceback (most recent call last):
  File "main_finetune.py", line 323, in <module>
    global_step, dice_val_best, global_step_best = train(
  File "main_finetune.py", line 263, in train
    for step, batch in enumerate(epoch_iterator):
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1356, in _next_data
    return self._process_data(data)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/croppad/dictionary.py", line 1171, in __call__
    self.randomize(label, fg_indices, bg_indices, image)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/croppad/dictionary.py", line 1153, in randomize
    self.centers = generate_pos_neg_label_crop_centers(
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/utils.py", line 512, in generate_pos_neg_label_crop_centers
    centers.append(correct_crop_centers(center, spatial_size, label_spatial_shape, allow_smaller))
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/utils.py", line 439, in correct_crop_centers
    raise ValueError("The size of the proposed random crop ROI is larger than the image size.")
ValueError: The size of the proposed random crop ROI is larger than the image size.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.croppad.dictionary.RandCropByPosNegLabeld object at 0x7f46042f4a60>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/data/dataset.py", line 97, in __getitem__
    return self._transform(index)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/data/dataset.py", line 792, in _transform
    return super()._transform(index_)
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/data/dataset.py", line 83, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/ai-team1/anaconda3/envs/uxnet3d/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f46042f4970>

May I ask where the problem is and how should I operate to repeat your experiment. Looking forward to your reply.

**Comment by SanmAIGO** [comment]
我使用的是AMOS2022数据，遵循了Unetr的数据划分，我的邮箱是xiaosenforai@gmail.com。

**Comment by SanmAIGO** [comment]
I use AMOS2022 data set from the web site https://zenodo.org/record/7155725#.Y0OOCOxBztM for, I don't have to change of data set, whether the error occurred. If yes, could you please send me your data division? (Preferably a json file with AMOS2022, FeTA2021 and FLARE2021 all data partitions). My email address is [xiaosenforai@gmail.com]. Thank you very much.

**Comment by dirtycomputer** [comment]
How was this problem finally solved?

**Comment by landonmax0** [comment]
Hello, I have also encountered the same problem. How did you solve it?
