### ISSUE TITLE
test_seg.py problem

### ISSUE THREAD

**Issue by Yffy123456** [MASILab/3DUX-Net#7]
i don't know how to deal with it
/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/io/dictionary.py", line 130, in __call__
    for key, meta_key, meta_key_postfix in self.key_iterator(d, self.meta_keys, self.meta_key_postfix):
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 370, in key_iterator
    raise KeyError(
KeyError: 'Key `image` of transform `LoadImaged` was missing in the data and allow_missing_keys==False.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7f95514f6130>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wf/yf/3DUX-Net-main/test_seg.py", line 102, in <module>
    for i, test_data in enumerate(test_loader):
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/data/dataset.py", line 97, in __getitem__
    return self._transform(index)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/data/dataset.py", line 792, in _transform
    return super()._transform(index_)
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/data/dataset.py", line 83, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/wf/anaconda3/envs/nnFormer0/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7f95514f66d0>

Process finished with exit code 1

**Comment by leeh43** [comment]
Hi, I just fix the key mismatch in test_seg.py. I also have tried with my latest trained model and it works well now. Please try with the latest version test_seg.py. 

Fyi: I will also upload the latest trained model and feel free to have a try on that.
